export const books = [
  {
    id: 2,
    title: "1984",
    slug: "1984-English",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    rating: 4.9,
    description: "Experience Orwell's masterpiece with immersive visuals and haunting soundscape.",
    video: "/1984-english.mp4",
    poster: "/1984-english.webp",
    readTime: "12 hrs",
    features: ["English Audio", "Sound Effects", "Animation"],
    language: "en",
  },
  {
    id: 3,
    title: "Alice in Wonderland",
    slug: "Alice-Wonderland",
    author: "Lewis Carroll",
    genre: "Fantasy",
    year: "1865",
    rating: 4.8,
    description: "Fall down the rabbit hole into a whimsical world of talking animals and magical adventures.",
    video: "/alice-wonderland.mp4",
    poster: "/alice-wonderland.webp",
    readTime: "6 hrs",
    features: ["Fantasy Animation", "Whimsical Music", "Character Voices"],
    language: "en",
  },

  {
    id: 12,
    title: "Snow Queen",
    slug: "Snow-Queen",
    author: "Hans Christian Andersen",
    genre: "Fairy Tale",
    year: "1844",
    rating: 4.7,
    description: "Another enchanting version of the beloved winter fairy tale with different artistic vision.",
    video: "/snow-queen.mp4",
    poster: "/snow-queen.webp",
    readTime: "4 hrs",
    features: ["Ice Magic", "Nordic Music", "Winter Animation"],
    language: "en",
  },
  {
    id: 6,
    title: "Lalka",
    slug: "Lalka",
    author: "Bolesław Prus",
    genre: "Realism",
    year: "1890",
    rating: 4.5,
    description: "A masterpiece of Polish literature exploring love, ambition, and social change.",
    video: "/lalka.mp4",
    poster: "/lalka.webp",
    readTime: "15 hrs",
    features: ["Period Drama", "Classical Music", "Historical Animation"],
    language: "pl",
  },
  {
    id: 7,
    title: "Macbeth",
    slug: "Macbeth",
    author: "William Shakespeare",
    genre: "Tragedy",
    year: "1606",
    rating: 4.8,
    description: "The Scottish play brought to life with dark visuals and dramatic performances.",
    video: "/macbeth.mp4",
    poster: "/macbeth.webp",
    readTime: "3 hrs",
    features: ["Shakespearean Audio", "Gothic Animation", "Dramatic Score"],
    language: "en",
  },
  {
    id: 8,
    title: "A Midsummer Night's Dream",
    slug: "Midsummer-Nights-Dream",
    author: "William Shakespeare",
    genre: "Comedy",
    year: "1595",
    rating: 4.7,
    description: "Enter the enchanted forest where fairies, lovers, and magic collide in delightful chaos.",
    video: "/midsummer-nights-dream.mp4",
    poster: "/midsummer-nights-dream.webp",
    readTime: "3 hrs",
    features: ["Fairy Magic", "Comedic Voice", "Forest Animation"],
    language: "en",
  },
  {
    id: 9,
    title: "Othello",
    slug: "Othello",
    author: "William Shakespeare",
    genre: "Tragedy",
    year: "1603",
    rating: 4.6,
    description: "A tale of jealousy, manipulation, and tragic love in Renaissance Venice.",
    video: "/othello.mp4",
    poster: "/othello.webp",
    readTime: "3 hrs",
    features: ["Venetian Setting", "Dramatic Audio", "Renaissance Art"],
    language: "en",
  },
  {
    id: 10,
    title: "Pharaon",
    slug: "Pharaon",
    author: "Bolesław Prus",
    genre: "Historical",
    year: "1895",
    rating: 4.5,
    description: "Journey to ancient Egypt in this epic tale of power, politics, and destiny.",
    video: "/pharaon.mp4",
    poster: "/pharaon.webp",
    readTime: "18 hrs",
    features: ["Ancient Egypt", "Epic Music", "Historical Animation"],
    language: "pl",
  },
  {
    id: 11,
    title: "Romeo and Juliet",
    slug: "Romeo-And-Juliet",
    author: "William Shakespeare",
    genre: "Romance",
    year: "1597",
    rating: 4.9,
    description: "The ultimate tale of star-crossed lovers brought to life with passion and beauty.",
    video: "/romeo-and-juliet.mp4",
    poster: "/romeo-and-juliet.webp",
    readTime: "3 hrs",
    features: ["Romantic Music", "Renaissance Art", "Passionate Audio"],
    language: "en",
  },
  {
    id: 1,
    title: "1984 (Polish)",
    slug: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    rating: 4.9,
    description: "Enter the totalitarian world of Big Brother with immersive visuals and haunting soundscape.",
    video: "/1984.mp4",
    poster: "/1984.webp",
    readTime: "12 hrs",
    features: ["Voice Acting", "Ambient Sound", "Animation"],
    language: "pl",
  },
  {
    id: 5,
    title: "Krolowa Sniegu",
    slug: "Krolowa-Sniegu",
    author: "Hans Christian Andersen",
    genre: "Fairy Tale",
    year: "1844",
    rating: 4.7,
    description: "A magical winter tale of friendship, love, and the power of a pure heart.",
    video: "/krolowa-sniegu.mp4",
    poster: "/krolowa-sniegu.webp",
    readTime: "4 hrs",
    features: ["Winter Magic", "Orchestral Music", "Animated Snow"],
    language: "pl",
  },

  {
    id: 4,
    title: "Tajny Agent",
    slug: "Conrad-Tajny-Agent",
    author: "Joseph Conrad",
    genre: "Thriller",
    year: "1907",
    rating: 4.6,
    description: "A gripping tale of espionage and political intrigue in Victorian London.",
    video: "/conrad-tajny-agent.mp4",
    poster: "/conrad-tajny-agent.webp",
    readTime: "10 hrs",
    features: ["Suspenseful Score", "Period Animation", "Voice Acting"],
    language: "pl",
  },
];
