import type { Book } from "@platform/utils/types.ts";

export const books: Book[] = [
  {
    id: 2,
    title: "1984",
    slug: "1984-English",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    rating: 4.9,
    description: "Experience Orwell's masterpiece with immersive visuals and haunting soundscape.",
    video: "/1984-english.v1.mp4",
    poster: "/1984-english.v1.webp",
    readTime: "12 hrs",
    features: ["English Audio", "Sound Effects", "Animation"],
    language: "en",
    phrases: ["Installing telescreens...", "Configuring thoughtcrime detection...", "Erasing the past...", "Activating thought police..."],
    type: "novel",
  },
  {
    id: 3,
    title: "Alice in Wonderland",
    slug: "Alice-Wonderland",
    author: "Lewis Carroll",
    genre: "Fantasy",
    year: "1865",
    rating: 4.8,
    description: "Fall down the rabbit hole into a whimsical world of talking animals and magical adventures.",
    video: "/alice-wonderland.v1.mp4",
    poster: "/alice-wonderland.v1.webp",
    readTime: "6 hrs",
    features: ["Fantasy Animation", "Whimsical Music", "Character Voices"],
    language: "en",
    phrases: [
      "Stretching reality...",
      "Shrinking logic...",
      "Resizing hallways...",
      "Ignoring all known physics...",
      "Painting the roses red...",
      "Calibrating curiosity...",
      "Consulting the Caterpillar...",
    ],
    type: "novel",
  },
  {
    id: 12,
    title: "Snow Queen",
    slug: "Snow-Queen",
    author: "Hans Christian Andersen",
    genre: "Fairy Tale",
    year: "1844",
    rating: 4.7,
    description: "Another enchanting version of the beloved winter fairy tale with different artistic vision.",
    video: "/snow-queen.v1.mp4",
    poster: "/snow-queen.v1.webp",
    readTime: "4 hrs",
    features: ["Ice Magic", "Nordic Music", "Winter Animation"],
    language: "en",
    phrases: ["Building snow palaces...", "Freezing summer dreams...", "Icing friendships...", "Crafting snowflakes...", "Conjuring frostbite..."],
    type: "novel",
  },
  {
    id: 6,
    title: "Lalka",
    slug: "Lalka",
    author: "Bolesław Prus",
    genre: "Powieść realistyczna",
    year: "1890",
    rating: 4.5,
    description: "Arcydzieło polskiej literatury zgłębiające miłość, ambicję i zmiany społeczne.",
    video: "/lalka.v1.mp4",
    poster: "/lalka.v1.webp",
    readTime: "13 godz. 20 min.",
    features: ["Dramat kostiumowy", "Muzyka klasyczna", "Animacja historyczna"],
    language: "pl",
    phrases: [
      "Polerowanie sklepowych witryn...",
      "Kształtowanie towarzyskich opinii...",
      "Bilansowanie ksiąg handlowych...",
      "Snucie romantycznych intryg...",
      "Negocjowanie perspektyw małżeńskich...",
    ],
    type: "powieść",
  },
  {
    id: 7,
    title: "Macbeth",
    slug: "Macbeth",
    author: "William Shakespeare",
    genre: "Tragedy",
    year: "1606",
    rating: 4.8,
    description: "The Scottish play brought to life with dark visuals and dramatic performances.",
    video: "/macbeth.v1.mp4",
    poster: "/macbeth.v1.webp",
    readTime: "3 hrs",
    features: ["Shakespearean Audio", "Gothic Animation", "Dramatic Score"],
    language: "en",
    phrases: [
      "Sharpening quills...",
      "Tuning the lute...",
      "Consulting the soothsayer...",
      "Polishing the crown jewels...",
      "Mulling a tragic flaw...",
      "Brewing toil and trouble...",
      "Assembling the groundlings...",
      "Checking for daggers...",
    ],
    type: "play",
  },
  {
    id: 8,
    title: "A Midsummer Night's Dream",
    slug: "Midsummer-Nights-Dream",
    author: "William Shakespeare",
    genre: "Comedy",
    year: "1595",
    rating: 4.7,
    description: "Enter the enchanted forest where fairies, lovers, and magic collide in delightful chaos.",
    video: "/midsummer-nights-dream.v1.mp4",
    poster: "/midsummer-nights-dream.v1.webp",
    readTime: "3 hrs",
    features: ["Fairy Magic", "Comedic Voice", "Forest Animation"],
    language: "en",
    phrases: ["Casting love spells...", "Chasing fairies...", "Taming mischievous spirits...", "Confusing lovers...", "Weaving magical forests..."],
    type: "play",
  },
  {
    id: 9,
    title: "Othello",
    slug: "Othello",
    author: "William Shakespeare",
    genre: "Tragedy",
    year: "1603",
    rating: 4.6,
    description: "A tale of jealousy, manipulation, and tragic love in Renaissance Venice.",
    video: "/othello.v1.mp4",
    poster: "/othello.v1.webp",
    readTime: "3 hrs",
    features: ["Venetian Setting", "Dramatic Audio", "Renaissance Art"],
    language: "en",
    phrases: ["Planting seeds of jealousy...", "Spinning webs of deceit...", "Perfecting tragic misunderstandings...", "Whispering falsehoods...", "Polishing dramatic irony..."],
    type: "play",
  },
  {
    id: 10,
    title: "Pharaon",
    slug: "Pharaon",
    author: "Bolesław Prus",
    genre: "Historical",
    year: "1895",
    rating: 4.5,
    description: "Journey to ancient Egypt in this epic tale of power, politics, and destiny.",
    video: "/pharaon.v1.mp4",
    poster: "/pharaon.v1.webp",
    readTime: "18 hrs",
    features: ["Ancient Egypt", "Epic Music", "Historical Animation"],
    language: "pl",
    phrases: [
      "Building the pyramids...",
      "Raising the temple of Amun...",
      "Carving the sphinxes...",
      "Painting hieroglyphs...",
      "Setting up the Nile...",
      "Creating mummies...",
      "Crowning the pharaoh...",
      "Building tombs...",
      "Carving obelisks...",
      "Painting papyrus...",
      "Setting up pyramids...",
      "Creating scarabs...",
    ],
    type: "novel",
  },
  {
    id: 11,
    title: "Romeo and Juliet",
    slug: "Romeo-And-Juliet",
    author: "William Shakespeare",
    genre: "Romance",
    year: "1597",
    rating: 4.9,
    description: "The ultimate tale of star-crossed lovers brought to life with passion and beauty.",
    video: "/romeo-and-juliet.v1.mp4",
    poster: "/romeo-and-juliet.v1.webp",
    readTime: "3 hrs",
    features: ["Romantic Music", "Renaissance Art", "Passionate Audio"],
    language: "en",
    phrases: ["Mixing love potions...", "Arranging secret meetings...", "Avoiding family feuds...", "Balcony climbing practice...", "Sending cryptic love letters..."],
    type: "play",
  },
  {
    id: 1,
    title: "1984 (Polish)",
    slug: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    rating: 4.9,
    description: "Enter the totalitarian world of Big Brother with immersive visuals and haunting soundscape.",
    video: "/1984.v1.mp4",
    poster: "/1984.v1.webp",
    readTime: "12 hrs",
    features: ["Voice Acting", "Ambient Sound", "Animation"],
    language: "pl",
    phrases: [
      "Big Brother is watching...",
      "Rewriting history...",
      "Monitoring your thoughts...",
      "Increasing chocolate rations...",
      "Preparing Room 101...",
      "Adjusting reality...",
      "Fighting thoughtcrime...",
    ],
    type: "novel",
  },
  {
    id: 5,
    title: "Krolowa Sniegu",
    slug: "Krolowa-Sniegu",
    author: "Hans Christian Andersen",
    genre: "Fairy Tale",
    year: "1844",
    rating: 4.7,
    description: "A magical winter tale of friendship, love, and the power of a pure heart.",
    video: "/krolowa-sniegu.v1.mp4",
    poster: "/krolowa-sniegu.v1.webp",
    readTime: "4 hrs",
    features: ["Winter Magic", "Orchestral Music", "Animated Snow"],
    language: "pl",
    phrases: ["Freezing hearts...", "Shattering mirrors...", "Chilling the air...", "Preparing ice castles...", "Summoning snowflakes..."],
    type: "novel",
  },
  {
    id: 4,
    title: "Tajny Agent",
    slug: "Conrad-Tajny-Agent",
    author: "Joseph Conrad",
    genre: "Thriller",
    year: "1907",
    rating: 4.6,
    description: "A gripping tale of espionage and political intrigue in Victorian London.",
    video: "/conrad-tajny-agent.v1.mp4",
    poster: "/conrad-tajny-agent.v1.webp",
    readTime: "10 hrs",
    features: ["Suspenseful Score", "Period Animation", "Voice Acting"],
    language: "pl",
    phrases: ["Encrypting secret messages...", "Plotting espionage...", "Shadowing informants...", "Meeting in dark alleys...", "Planting evidence..."],
    type: "novel",
  },
  {
    id: 13,
    title: "Secret Agent",
    slug: "Conrad-Secret-Agent",
    author: "Joseph Conrad",
    genre: "Thriller",
    year: "1907",
    rating: 4.6,
    description: "A gripping tale of espionage and political intrigue in Victorian London.",
    video: "/conrad-secret-agent.v1.mp4",
    poster: "/conrad-secret-agent.v1.webp",
    readTime: "10 hrs",
    features: ["Suspenseful Score", "Period Animation", "Voice Acting"],
    language: "en",
    phrases: ["Encrypting secret messages...", "Plotting espionage...", "Shadowing informants...", "Meeting in dark alleys...", "Planting evidence..."],
    type: "novel",
  },
];
