/**
 * Shared recursive leaf-element extraction logic.
 *
 * Used by:
 *   - build-leaf-index-mappings.ts (migration tool)
 *   - Eventually: player htmlNormalizer.ts + pipeline getParagraphsFromChapterWithText.ts
 *
 * Leaf elements: content elements that get a data-index (stop recursing)
 * Container elements: structural wrappers (recurse into children)
 */

import type * as cheerio from "cheerio";

const LEAF_TAGS = new Set([
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "li",
  "td",
  "th",
  "dt",
  "dd",
  "figcaption",
  "hr",
  "cite",
]);

const CONTAINER_TAGS = new Set([
  "blockquote",
  "div",
  "section",
  "table",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "ol",
  "ul",
  "dl",
  "header",
  "footer",
  "figure",
  "aside",
  "hgroup",
]);

export interface LeafElement {
  index: number;
  text: string;
  tag: string;
  /** Index of the direct-child ancestor (for mapping back to old system) */
  directChildIndex: number;
}

/**
 * Check if an element has any child elements (not just text nodes).
 */
function hasChildElements(
  $: cheerio.CheerioAPI,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  el: any,
): boolean {
  return $(el).children().length > 0;
}

/**
 * Recursively extract leaf elements from a chapter section.
 *
 * Rules:
 * - If element is a LEAF tag → add it (don't recurse deeper)
 * - If element is a CONTAINER tag → recurse into children
 * - If element is a CONTAINER with no child elements (just text) → treat as leaf
 * - Skip empty elements
 * - Format B speaker blocks (<div data-speaker data-label>) are handled specially:
 *   they generate a speaker label + their child <p>s, same as current system
 */
export function extractLeafElements($: cheerio.CheerioAPI, chapterNum: number): LeafElement[] {
  const section = $(`[data-chapter="${chapterNum}"]`);
  const leaves: LeafElement[] = [];
  let leafIndex = 0;
  let directChildIdx = 0;

  section.children().each((_, directChild) => {
    const currentDirectChildIdx = directChildIdx++;
    const tag = directChild.tagName?.toLowerCase();
    if (!tag) return;

    const $child = $(directChild);

    // Format B speaker block — handle same as current system
    // (generates speaker label + content paragraphs)
    if (tag === "div" && $child.attr("data-speaker") && $child.attr("data-label")) {
      const label = $child.attr("data-label") || "";
      // Speaker label (generated by player)
      leaves.push({
        index: leafIndex++,
        text: label,
        tag: "speaker-label",
        directChildIndex: currentDirectChildIdx,
      });
      // Content paragraphs inside the speaker block
      $child.children().each((_, innerChild) => {
        const innerTag = innerChild.tagName?.toLowerCase();
        if (innerTag === "p") {
          leaves.push({
            index: leafIndex++,
            text: $(innerChild).text().trim(),
            tag: "p",
            directChildIndex: currentDirectChildIdx,
          });
        }
      });
      return;
    }

    // Recurse into this direct child
    function recurse(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      el: any,
    ): void {
      const elTag = el.tagName?.toLowerCase();
      if (!elTag) return;

      const $el = $(el);
      const text = $el.text().trim();

      // Skip empty elements
      if (!text) return;

      // Leaf element → add it
      if (LEAF_TAGS.has(elTag)) {
        leaves.push({
          index: leafIndex++,
          text: text.slice(0, 120),
          tag: elTag,
          directChildIndex: currentDirectChildIdx,
        });
        return;
      }

      // Container element → recurse into children (or treat as leaf if no child elements)
      if (CONTAINER_TAGS.has(elTag)) {
        if (!hasChildElements($, el)) {
          // Container with only text, no child elements → treat as leaf
          leaves.push({
            index: leafIndex++,
            text: text.slice(0, 120),
            tag: elTag,
            directChildIndex: currentDirectChildIdx,
          });
          return;
        }
        // Recurse into children
        $el.children().each((_, child) => {
          recurse(child);
        });
        return;
      }

      // Unknown tag with text → treat as leaf (safe default)
      leaves.push({
        index: leafIndex++,
        text: text.slice(0, 120),
        tag: elTag,
        directChildIndex: currentDirectChildIdx,
      });
    }

    recurse(directChild);
  });

  return leaves;
}

/**
 * Get direct children as flat list (current/old indexing system).
 */
export function extractDirectChildren($: cheerio.CheerioAPI, chapterNum: number): LeafElement[] {
  const section = $(`[data-chapter="${chapterNum}"]`);
  const elements: LeafElement[] = [];
  let index = 0;
  let directChildIdx = 0;

  section.children().each((_, child) => {
    const tag = child.tagName?.toLowerCase();
    if (!tag) return;
    const $child = $(child);
    const text = $child.text().trim();
    if (!text) {
      directChildIdx++;
      return;
    }

    const currentDirectChildIdx = directChildIdx++;

    // Format B speaker block — same handling as player
    if (tag === "div" && $child.attr("data-speaker") && $child.attr("data-label")) {
      const label = $child.attr("data-label") || "";
      elements.push({
        index: index++,
        text: label,
        tag: "speaker-label",
        directChildIndex: currentDirectChildIdx,
      });
      $child.children().each((_, innerChild) => {
        if (innerChild.tagName?.toLowerCase() === "p") {
          elements.push({
            index: index++,
            text: $(innerChild).text().trim().slice(0, 120),
            tag: "p",
            directChildIndex: currentDirectChildIdx,
          });
        }
      });
      return;
    }

    elements.push({
      index: index++,
      text: text.slice(0, 120),
      tag,
      directChildIndex: currentDirectChildIdx,
    });
  });

  return elements;
}
