    server {
      server_name wh.bookg.aws.lucetius.pl;

      include /usr/local/openresty/nginx/conf/snippets/bookg.aws.lucetius.pl-ssl.conf;

      location / {
        set $upstream "webhook:3001";
        include /usr/local/openresty/nginx/conf/snippets/upstream.conf;
      }
    }
