import type { BackgroundsForBook } from "@/ui/getBackgroundsForBook";

export const backgroundsForBook: BackgroundsForBook = [
  { chapter: 1, startParagraph: 0, file: "chapter-1-background.mp4" },
  // { chapter: 1, startParagraph: 0, file: "dom-laponki.mp4" },
  { chapter: 2, startParagraph: 0, file: "krolowa-chapter-2-paragraph-0-loop.mp4" },
  { chapter: 2, startParagraph: 35, file: "krolowa-chapter-2-paragraph-35.mp4" },
  { chapter: 2, startParagraph: 42, file: "snow-covered-forest.mp4" },
  { chapter: 3, startParagraph: 0, file: "riverbank.mp4" },
  { chapter: 3, startParagraph: 20, file: "cottage-with-flower-covered-walls.mp4" },
  { chapter: 3, startParagraph: 43, file: "krolowa-chapter-3-paragraph-43.mp4" },
  { chapter: 4, startParagraph: 0, file: "forest-first-snow.mp4" },
  { chapter: 4, startParagraph: 22, file: "palace-interior.mp4" },
  { chapter: 4, startParagraph: 39, file: "gerda-w-palacu-fixed.mp4" },
  { chapter: 5, startParagraph: 0, file: "forest-at-night.mp4" },
  { chapter: 5, startParagraph: 11, file: "chapter-5-zamek-zbojow.mp4" },
  { chapter: 5, startParagraph: 36, file: "forest-at-night.mp4" },
  { chapter: 5, startParagraph: 40, file: "frozen-plain.mp4" },
  { chapter: 6, startParagraph: 0, file: "dom-laponki.mp4" },
  { chapter: 6, startParagraph: 6, file: "finland-cottage.mp4" },
  { chapter: 6, startParagraph: 23, file: "krolowa-chapter-6-23.mp4" },
  { chapter: 6, startParagraph: 28, file: "ice-castle-exterior.mp4" },
  { chapter: 7, startParagraph: 0, file: "ice-castle-interior.mp4" },
  { chapter: 7, startParagraph: 4, file: "krolowa-chapter-7-4.mp4" },
  { chapter: 7, startParagraph: 27, file: "summer-garden.mp4" },
  { chapter: 7, startParagraph: 40, file: "krolowa-town-loop2.mp4" },
  { chapter: 7, startParagraph: 43, file: "grandmother-house.mp4" },
];
