worker_processes auto;
events { worker_connections 1024; }
env REDIS_HOST;
env REDIS_PORT;
env REDIS_PASSWORD;
http {
    resolver 127.0.0.11 ipv6=off valid=30s;
    lua_package_path '/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/nginx/conf/lua/?.lua;;';
    map $http_upgrade $connection_upgrade {
        default close;
        websocket upgrade;
    }
    server_tokens off;

    error_log  /dev/stderr  info;

    include /usr/local/openresty/nginx/conf/sites-enabled/*.conf;
}
