name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: false

      - run: corepack enable
      - name: Setup Bun and install dependencies
        uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun typecheck:ci
      - run: bun lint:ci
      - run: bun prettier:check
