name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        #     !apps/player/public_books
        #   sparse-checkout-cone-mode: false
      - run: ls -al
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      # - run: pnpm test
      # - run: pnpm typecheck:ci
      # - run: pnpm lint:ci
      - run: pnpm prettier:check
      # - name: Build project
      #   run: pnpm build public_books/Krolowa-Sniegu
