name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest-m
    environment: aws
    env:
      ROLE_ARN: ${{ vars.AWS_ROLE_TO_ASSUME || '' }}
    steps:
      - name: Set-up s5cmd
        uses: peak/action-setup-s5cmd@main
        with:
          version: v2.0.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Set dynamic environment variables
        id: set_vars
        run: |
          REPOSITORY=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPOSITORY=${REPOSITORY}" >> $GITHUB_ENV
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For Pull Requests
            BRANCH_NAME=$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9')
            echo "ASSET_CONTEXT=branches/${BRANCH_NAME}" >> $GITHUB_ENV
            echo "IS_PRODUCTION=false" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9')
            echo "ASSET_CONTEXT=prod" >> $GITHUB_ENV
            echo "IS_PRODUCTION=true" >> $GITHUB_ENV
          fi

      - name: Setup Bun and install dependencies
        uses: oven-sh/setup-bun@v1
      - run: pnpm install

      #      - name: Build local artifacts (for S3 upload)
      #        run: pnpm build:docker

      - name: Build
        run: pnpm build:docker:with-books
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CI: true

      - name: Deploy assets to S3
        env:
          ASSET_CONTEXT: ${{ env.ASSET_CONTEXT }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          BRANCHES_DISTRIBUTION_ID: ${{ vars.BRANCHES_DISTRIBUTION_ID }}
          PROD_DISTRIBUTION_ID: ${{ vars.PROD_DISTRIBUTION_ID }}
        run: bash ./update.sh --with-books
